name: hello-world
on: push
jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: read-from-disk 
        run: sh -c 'cat /tmp/now || true'
      - name: write-on-disk 
        run: sh -c 'date > /tmp/now'
